#pragma once

#define M2J_STR_(x) #x
#define M2J_STR(x) M2J_STR_(x)
#define M2J_MAJOR_VERSION 1
#define M2J_MINOR_VERSION 0
#define M2J_PATCH_VERSION 0
#define M2J_VERSION \
    M2J_STR(M2J_MAJOR_VERSION) "." M2J_STR(M2J_MINOR_VERSION) "." M2J_STR(M2J_PATCH_VERSION)
